
<img align="right" width="125" src="https://www.ou.nl/documents/40554/3255217/Logo_OU.jpg"/>

<br>


<center> <font size ="6" color='red'> AI for Prescriptive Analysis </font></center>
<br> 
<center> <font size ="5" color='red'> Discrete Event Simulation in Python</font></center>
<br>

--------------------------

In [1]:
online = True; gitfolder = ''

if online:
    %pip install ortools
    !wget https://raw.githubusercontent.com/muratfirat78/ProductionPlanning/refs/heads/main/src/remotemanager.py
    from remotemanager import *
    for mydir,files in downloads.items():
        for filename in files: 
            if not filename in os.listdir(source_directory):
                !wget "{mydir}{filename}"

from controller import *
mycontroller = Controller(); mycontroller.setOnline(online); mycontroller.setGitDir(gitfolder); mycontroller.checkUseCases()
mytab = mycontroller.GetDashBoard(); tab_set = widgets.Tab([mytab]); tab_set.set_title(0,'Operations Planning'); tab_set

ImportError: DLL load failed while importing _pywraplp: An Application Control policy has blocked this file.

In [4]:
pip install ortools

Requirement already satisfied: ortools in C:\Users\MFI\anaconda3\envs\MFI\Lib\site-packages (9.15.6755)
Requirement already satisfied: absl-py>=2.0.0 in C:\Users\MFI\anaconda3\envs\MFI\Lib\site-packages (from ortools) (2.4.0)
Requirement already satisfied: numpy>=2.0.2 in C:\Users\MFI\anaconda3\envs\MFI\Lib\site-packages (from ortools) (2.4.3)
Requirement already satisfied: pandas>=2.0.0 in C:\Users\MFI\anaconda3\envs\MFI\Lib\site-packages (from ortools) (3.0.1)
Requirement already satisfied: protobuf<6.34,>=6.33.1 in C:\Users\MFI\anaconda3\envs\MFI\Lib\site-packages (from ortools) (6.33.6)
Requirement already satisfied: typing-extensions>=4.12 in C:\Users\MFI\anaconda3\envs\MFI\Lib\site-packages (from ortools) (4.15.0)
Requirement already satisfied: immutabledict>=3.0.0 in C:\Users\MFI\anaconda3\envs\MFI\Lib\site-packages (from ortools) (4.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\MFI\anaconda3\envs\MFI\Lib\site-packages (from pandas>=2.0.0->ortools) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\MFI\anaconda3\envs\MFI\Lib\site-packages (from pandas>=2.0.0->ortools) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\MFI\anaconda3\envs\MFI\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->ortools) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# event creation: OutputBuffer -> Trailer Loading 
#                 InputBuffer -> Machine Setup
 

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os

exec_df = pd.read_csv(os.path.join("..", "data", "simulation", "EventExecutionData.csv"))

diagnose = True

print("Item batches: "+str(len(exec_df["Items"].unique())))

for batch in exec_df["Items"].unique():
    if pd.isnull(batch):
        continue
    sub_df = exec_df[exec_df["Items"] == batch]
    sub_df = sub_df.sort_values(['SimTime'])
    start = sub_df.iloc[0, sub_df.columns.get_loc('Location')]
    end = sub_df.iloc[len(sub_df)-1, sub_df.columns.get_loc('Location')]

    if batch =="1~17":
        display(sub_df)
    
        print("______________________________")
    

op1_df = exec_df[exec_df["Resource"] == "Operator 1"]


display(op1_df.head(20))

op2_df = exec_df[exec_df["Resource"] == "Operator 2"]


display(op2_df.head(20))

Item batches: 0

Empty DataFrame
Columns: [ID, Product, Product/ID, Quantity To Produce, Deadline, Reference, Work Orders/Work Center, Work Orders/Work Center/ID, Processing Machine, Work Orders/Operation, Operation Order, Work Orders/Expected Duration, Work Orders/Start, Work Orders/End, Work Orders/Status, Tardy, Lateness (days), EventName, EventID, ProgressSteps, Items, Resource, Equipment, Location, SimTime, Date]
Index: []

[0 rows x 26 columns]

Empty DataFrame
Columns: [ID, Product, Product/ID, Quantity To Produce, Deadline, Reference, Work Orders/Work Center, Work Orders/Work Center/ID, Processing Machine, Work Orders/Operation, Operation Order, Work Orders/Expected Duration, Work Orders/Start, Work Orders/End, Work Orders/Status, Tardy, Lateness (days), EventName, EventID, ProgressSteps, Items, Resource, Equipment, Location, SimTime, Date]
Index: []

[0 rows x 26 columns]

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os

exec_df = pd.read_csv(os.path.join("..", "data", "simulation", "EventExecutionData.csv"))

diagnose = True

print("Item batches: "+str(len(exec_df["Items"].unique())))

for batch in exec_df["Items"].unique():
    if pd.isnull(batch):
        continue
    sub_df = exec_df[exec_df["Items"] == batch]
    sub_df = sub_df.sort_values(['SimTime'])
    start = sub_df.iloc[0, sub_df.columns.get_loc('Location')]
    end = sub_df.iloc[len(sub_df)-1, sub_df.columns.get_loc('Location')]

    if batch !="1~17":
        display(sub_df)
    
        print("______________________________")
    

#process_df = exec_df[exec_df["EventName"] == "Machine Processing"]

for myloc in exec_df["Location"].unique():
    print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
    print("Location: ",myloc)
    sub_df = exec_df[exec_df["Location"] == myloc]
    sub_df  = sub_df[(sub_df["EventName"] == "Machine Setup") | (sub_df["EventName"] =="Machine Loading") | (sub_df["EventName"] == "Machine Processing") | (sub_df["EventName"] == "Machine Unloading")]
    if diagnose and len(sub_df)  > 0:
        for i,r in sub_df.iterrows():
            print(r["EventName"],r["EventID"],r["Location"],r["SimTime"])
        
        #display(sub_df)

    


print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
exec_df = pd.read_csv(os.path.join("..", "data", "simulation", "BufferData.csv"))

for buff in exec_df["BufferName"].unique():
    sub_df = exec_df[exec_df["BufferName"] == buff]
    agg_df = sub_df.groupby(['BufferName','Time'])['No.Items'].max().reset_index()
    agg_df = agg_df.rename(columns={agg_df.columns[-1]: "No.Items"})

    if buff in ["Central_Output","Central_Input"]:
        sns.barplot(agg_df, x="Time", y="No.Items", legend=False).set_title(buff)
        plt.xticks(rotation=45)
        plt.show()
        
        display(agg_df.head(100))
        print("______________________________")

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os

exec_df = pd.read_csv(os.path.join("..", "data", "simulation", "EventExecutionData.csv"))

diagnose = True

print("Item batches: "+str(len(exec_df["Items"].unique())))

for batch in exec_df["Items"].unique():
    if pd.isnull(batch):
        continue
    sub_df = exec_df[exec_df["Items"] == batch]
    sub_df = sub_df.sort_values(['SimTime'])
    start = sub_df.iloc[0, sub_df.columns.get_loc('Location')]
    end = sub_df.iloc[len(sub_df)-1, sub_df.columns.get_loc('Location')]

    if batch !="1~17":
        display(sub_df)
    
        print("______________________________")
    

#process_df = exec_df[exec_df["EventName"] == "Machine Processing"]

for myloc in exec_df["Location"].unique():
    print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
    print("Location: ",myloc)
    sub_df = exec_df[exec_df["Location"] == myloc]
    sub_df  = sub_df[(sub_df["EventName"] == "Machine Setup") | (sub_df["EventName"] =="Machine Loading") | (sub_df["EventName"] == "Machine Processing") | (sub_df["EventName"] == "Machine Unloading")]
    if diagnose and len(sub_df)  > 0:
        for i,r in sub_df.iterrows():
            print(r["EventName"],r["EventID"],r["Location"],r["SimTime"])
        
        #display(sub_df)

    


print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
exec_df = pd.read_csv(os.path.join("..", "data", "simulation", "BufferData.csv"))

for buff in exec_df["BufferName"].unique():
    sub_df = exec_df[exec_df["BufferName"] == buff]
    agg_df = sub_df.groupby(['BufferName','Time'])['No.Items'].max().reset_index()
    agg_df = agg_df.rename(columns={agg_df.columns[-1]: "No.Items"})

    if buff in ["Central_Output","Central_Input"]:
        sns.barplot(agg_df, x="Time", y="No.Items", legend=False).set_title(buff)
        plt.xticks(rotation=45)
        plt.show()
        
        display(agg_df.head(100))
        print("______________________________")

In [ ]:
import pandas as pd

location_df = pd.read_csv(os.path.join("..", "data", "simulation", "LocationData.csv"))

for entity in location_df["EntityID"].unique():
    sub_df = location_df[location_df["EntityID"] == entity]
    display(sub_df)
    print("______________________________")

In [ ]:
# Importing the matplotlib.pyplot
import matplotlib.pyplot as plt

# Declaring a figure "gnt"
fig, gnt = plt.subplots()

# Setting Y-axis limits
gnt.set_ylim(0, 50)

# Setting X-axis limits
gnt.set_xlim(0, 160)

# Setting labels for x-axis and y-axis
gnt.set_xlabel('seconds since start')
gnt.set_ylabel('Processor')

# Setting ticks on y-axis
gnt.set_yticks([15, 25, 35])
# Labelling tickes of y-axis
gnt.set_yticklabels(['1', '2', '3'])

# Setting graph attribute
gnt.grid(True)

# Declaring a bar in schedule
gnt.broken_barh([(40, 50)], (30, 9), facecolors =('tab:orange'))

# Declaring multiple bars in at same level and same width
gnt.broken_barh([(110, 10), (150, 10)], (10, 9),
                         facecolors ='tab:blue')

gnt.broken_barh([(10, 50), (100, 20), (130, 10)], (20, 9),
                                  facecolors =('tab:red'))

In [ ]:
import pandas as pd

exec_df = pd.read_csv(os.path.join("..", "data", "simulation", "EventExecutionData.csv"))

demands_df = exec_df.groupby(['Items','ID','Product','Work Orders/Operation','EventName','EventID','Resource','Date'])['SimTime'].agg(lambda x:list(x)).reset_index()

for demand in demands_df['ID'].unique():
    demand_df = demands_df[demands_df["ID"] == demand]
    demand_df['Date']  = pd.to_datetime(demand_df['Date'], format="%Y-%m-%d %H:%M:%S")
    display(demand_df)

In [ ]:
import pandas as pd 

milp_schedule_df = pd.read_csv(os.path.join("..", "data", "schedules", "TBRM_Plan_2026-08-19_R10_2026-09-01.csv"))

sim_schedule_df = pd.read_csv(os.path.join("..", "data", "simulation", "EventExecutionData.csv"))

sim_schedule_df = sim_schedule_df[["ID","Product","Product/ID","Quantity To Produce","Deadline","Reference","Work Orders/Work Center","Work Orders/Work Center/ID","Work Orders/Operation","Operation Order","Work Orders/Expected Duration","Work Orders/Start(SIM)","Work Orders/End(SIM)","Work Orders/Status(SIM)","Tardy(SIM)","Lateness (days)(SIM)"]]

schedule_df = pd.merge(milp_schedule_df, sim_schedule_df,  how="left", on=["ID","Product","Product/ID","Quantity To Produce","Deadline","Reference","Work Orders/Work Center","Work Orders/Work Center/ID","Work Orders/Operation","Operation Order","Work Orders/Expected Duration"])

schedule_df.to_csv(os.path.join("..", "data", "schedules", "Combined_Schedule.csv"),index = False)

In [ ]:
import pandas as pd

events_df = pd.read_csv("EventExecutionData.csv")

products_df = events_df[["Product","Product/ID"]]
events_df = events_df.drop(columns=["Product/ID"])
events_df = events_df[['ID', 'Product','Quantity To Produce', 'Deadline']]
print(events_df.columns)
events_df = pd.merge(left = events_df, right = products_df,  how="left", on=["Product"])
print(events_df.columns)

In [ ]:
import pandas as pd


sales_df = pd.read_csv("company_sales_data.csv")
sales_df = sales_df[["month_number","facecream","facewash","total_units","total_profit"]]

sales_df = sales_df[sales_df["month_number"] >= 4]
sales_df.head()

In [ ]:
import numpy as np
print(np.arange(10))
print(np.arange(2, 10, dtype=np.float64))

In [ ]:
import numpy as np

print(np.eye(3)); print(np.eye(3, 5))
print(np.diag([1, 2, 3]))
np.diag([1, 2, 3], 1)

In [ ]:
import numpy as np

print(np.ndarray(shape=(2,2), dtype=np.float64, order='F'))

a = np.array([[1, 2], [3, 4]]); print(np.diag(a))
np.ndarray(shape=(2,2), dtype=np.float64, order='F')

In [ ]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
np.diag(a)

In [ ]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'data': range(6)}, columns=['key', 'data'])

print(df.head())
agg_df= df.groupby(['key']).agg(lambda x:list(x)).reset_index()
agg_df = agg_df.rename(columns={[x for x in agg_df.columns][-1]: 'numbers'})

agg_df.head()

In [ ]:
import math 
import random 
import numpy as np

demand_weight = 10000 # kg
avg_batch_weight = 500 # kg per container
no_batches = math.ceil(demand_weight/avg_batch_weight)
bag_ratio = 0.6; bag_weight_range = range(10,15); box_weight_range = range(25,40) # in kg.
nr_destinations = 15; priorities = [1,2,3]
destinations = [str(x) for x in range(nr_destinations)]
destination_probs = [random.random() for x in range(nr_destinations)]
priority_probs = [random.random() for x in range(len(priorities))]
prob_sum = sum(destination_probs); prio_sum = sum(priority_probs)
destination_probs = [x/prob_sum for x in destination_probs]  # make sum to one. 
priority_probs = [x/prio_sum for x in priority_probs]  # make sum to one. 
destination_probs = np.cumsum(destination_probs); priority_probs = np.cumsum(priority_probs)

remaining_weight = demand_weight

def sampleFromProbList(itemlist,probabilitylist):
    prob_samp = random.random()

    for itemid in range(len(itemlist)):
            if probabilitylist[itemid] > prob_samp:
                return itemlist[itemid]

    return None


print("Batches: ",no_batches)

demand_df = pd.DataFrame(columns=["ShipmentBatch","ShipmentType","Priority","Weight","Destination"])

for batchid in range(no_batches): # here the atches for each container is created.
    batchweight = 0 
    while batchweight < avg_batch_weight:
        shiptype = "Bag" if  random.random() <= bag_ratio else "Box"
        shipweight = random.choice(bag_weight_range) if shiptype == "Bag" else random.choice(box_weight_range)    
        batchweight+=shipweight
        remaining_weight-= shipweight         
        shipmentdata = {"ShipmentBatch":batchid,"ShipmentType":shiptype,"Priority":sampleFromProbList(priorities,priority_probs)
                        ,"Weight":shipweight,"Destination":sampleFromProbList(destinations,destination_probs)} 
        demand_df.loc[len(demand_df)]= shipmentdata

    if remaining_weight <= 0:
        break

print(demand_df["ShipmentBatch"].unique())
print("remaining_weight: ",remaining_weight," total shipments: ",len(demand_df))
demand_df.head(10)
    
        
    
demand_df.to_csv(os.path.join("Logistics_demand.csv"),index = False)

In [2]:
import os
os.add_dll_directory("C://Users/MFI/Anaconda3/DLLs")